name: Validate Pull Requests

on:
  pull_request:
    branches:
      - '*'
      - '!master'

jobs:
  validate-pull-requests:
    runs-on: ubuntu-latest
    env:
      PR_NUMBER: ${{ github.event.number }}
      GH_API_TOKEN: ${{ secrets.GH_API_TOKEN }}

    steps:
    - name: Show the PR number
      run: |
        echo "The PR number is: $PR_NUMBER"

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r .github/scripts/requirements.txt

    - name: Validate PR release
      run: |
        echo "Validating PR release"
        python .github/scripts/validate_release.py